<% if ENV['DATABASE_ADAPTER'] == 'mysql2' %>
default: &default
  host: 127.0.0.1
  port: 3306
  adapter: mysql2
  username: root
  encoding: utf8

test:
  primary:
    <<: *default
    database: annotaterb_test
<% end %>

<% if ENV['DATABASE_ADAPTER'] == 'pg' %>
default: &default
  host: 127.0.0.1
  port: 5432
  adapter: postgresql
  username: postgres
  encoding: utf8

test:
  primary:
    <<: *default
    database: annotaterb_test
<% end %>

<% if ENV['DATABASE_ADAPTER'] == 'sqlite3' %>
default: &default
  adapter: sqlite3

test:
  primary:
    <<: *default
    database: db/test.sqlite3
<% end %>

