version: 2.1

workflows:
  test:
    jobs:
      - rake_spec:
          name: test_ruby-<< matrix.ruby_version >>_database-<< matrix.database_adapter >>
          matrix:
            parameters:
              ruby_version:
                - '3.2.2'
                - '3.1.4'
                - '3.0.5'
                - '2.7.6'
              database_adapter:
                - 'mysql2'
                - 'pg'
                - 'sqlite3'

executors:
  ruby:
    parameters:
      ruby_version:
        type: string
    docker:
      - image: cimg/ruby:<< parameters.ruby_version >>
      - image: cimg/mysql:8.0
      - image: cimg/postgres:15.3

jobs:
  rake_spec:
    parameters:
      ruby_version:
        description: Ruby version
        type: string
      database_adapter:
        description: Database adapter
        type: string
    executor:
      name: ruby
      ruby_version: << parameters.ruby_version >>
    environment:
      DATABASE_ADAPTER: << parameters.database_adapter >>
    steps:
      - checkout
      - run:
          name: Wait for MySQL
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 1m
      - run:
          name: Wait for PostgreSQL
          command: dockerize -wait tcp://127.0.0.1:5432 -timeout 1m
      - run:
          name: Bundle Install
          command: bundle install
      - run:
          name: Run Integration Tests
          command: bundle exec rake spec:integration
