#!/usr/bin/env ruby
# frozen_string_literal: true

unless File.exist?('./Rakefile') || File.exist?('./Gemfile')
  abort 'Please run annotate from the root of the project.'
end

begin
  require 'bundler'
  Bundler.setup
rescue StandardError
end

$LOAD_PATH.unshift("#{__dir__}/../lib")

require 'annotate_rb'

exit_status = ::AnnotateRb::Runner.run(ARGV)

# TODO: Return exit status
# exit exit_status