#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.unshift("#{__dir__}/../lib")

require 'annotate_rb'

exit_status = ::AnnotateRb::Runner.run(ARGV)

# TODO: Return exit status
# exit exit_status