#!/usr/bin/env ruby

unless File.exist?('./Rakefile') || File.exist?('./Gemfile')
  abort 'Please run annotate from the root of the project.'
end

require 'rubygems'
begin
  require 'bundler'
  Bundler.setup
rescue StandardError
end

here = File.expand_path(File.dirname __FILE__)
$LOAD_PATH << "#{here}/../lib"

require 'annotate_rb'


options = ::AnnotateRb::Options.from({}, {})
AnnotateRb::RakeBootstrapper.call(options)

if options[:models]
  # Eager load Models when we're annotating models
  AnnotateRb::EagerLoader.call(options)

  puts "Annotating models"
  AnnotateRb::ModelAnnotator::Annotator.send(options[:target_action], options)
end

if options[:routes]
  puts "Annotating routes"
  AnnotateRb::RouteAnnotator::Annotator.send(options[:target_action], options)
end
